LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'mat4'
OUTPUT_DIR: '../outputs'
NUM_WORKERS: 0
MODEL_CONFIG: 'configs/WHAM/yamls/model_base.yaml'
FLIP_EVAL: True

TRAIN:
  STAGE: 'stage2'
  CHECKPOINT: 'WHAM/checkpoints/wham_vit_bedlam_w_3dpw.pth.tar'

MODEL:
  BACKBONE: 'vit'